import { politappAuthReady } from "../js/auth-guard.js";

const MODULES=[
  {id:"dashboard",label:"Visão geral",roles:["admin","gestao","operacoes"]},
  {id:"demandas",label:"Demandas e protocolos",roles:["admin","gestao","operacoes"],description:"Triagem, responsáveis, prazos, prioridades e histórico de cada solicitação."},
  {id:"cidadaos",label:"Cidadãos e lideranças",roles:["admin","gestao","operacoes"],description:"Cadastro unificado, territórios, temas de interesse e relacionamento."},
  {id:"agenda",label:"Agenda institucional",roles:["admin","gestao","operacoes"],description:"Compromissos, audiências, visitas, eventos e responsáveis."},
  {id:"projetos",label:"Projetos e entregas",roles:["admin","gestao"],description:"Metas, iniciativas, emendas, entregas e acompanhamento executivo."},
  {id:"comunicacao",label:"Comunicação",roles:["admin","gestao"],description:"Calendário editorial, aprovações, Meta, campanhas e ativos digitais."},
  {id:"territorios",label:"Territórios",roles:["admin","gestao"],description:"Demandas e indicadores organizados por bairro, município e região."},
  {id:"relatorios",label:"Relatórios",roles:["admin","gestao"],description:"Indicadores operacionais, produtividade, atendimento e prestação de contas."},
  {id:"administracao",label:"Administração e RBAC",roles:["admin"],description:"Usuários, equipes, perfis de acesso, unidades e trilha de auditoria."}
];
const ROLE_LABEL={admin:"Administrador",gestao:"Gestão",operacoes:"Operações"};
const token=()=>localStorage.getItem("politapp_token")||"";
async function api(resource){const q=token()?`?_token=${encodeURIComponent(token())}`:"";const r=await fetch(`/api/erp/${resource}${q}`,{credentials:"include",cache:"no-store"});return r.json()}
function menu(role){const el=document.getElementById("erpMenu");el.replaceChildren();for(const m of MODULES.filter(x=>x.roles.includes(role))){const b=document.createElement("button");b.textContent=m.label;b.dataset.module=m.id;b.addEventListener("click",()=>openModule(m.id,role));el.append(b)}}
function active(id){document.querySelectorAll("#erpMenu button").forEach(b=>b.classList.toggle("active",b.dataset.module===id))}
function openModule(id,role){active(id);document.querySelector(".sidebar").classList.remove("open");const dash=document.getElementById("dashboard"),view=document.getElementById("moduleView"),m=MODULES.find(x=>x.id===id);document.getElementById("pageTitle").textContent=m?.label||"ERP";document.getElementById("breadcrumb").textContent=`Gestão / ${m?.label||"ERP"}`;if(id==="dashboard"){dash.hidden=false;view.hidden=true;return}dash.hidden=true;view.hidden=false;view.replaceChildren();const grid=document.createElement("div");grid.className="module-grid";const cards=[m?.description,"Fluxos e indicadores configuráveis por gabinete.",role==="admin"?"Você pode administrar permissões deste módulo.":"Seu acesso respeita o perfil e a unidade vinculada."];for(const [i,text] of cards.entries()){const c=document.createElement("article");c.className="module-card";const h=document.createElement("h3");h.textContent=i?i===1?"Estrutura preparada":"Controle de acesso":m.label;const p=document.createElement("p");p.textContent=text;const tag=document.createElement("span");tag.className="tag";tag.textContent=i?"PRÓXIMA ETAPA":"MÓDULO ERP";c.append(h,p,tag);grid.append(c)}view.append(grid)}
function renderSummary(d){const values=[['Demandas abertas',d.demandsOpen||0],['Atendimentos hoje',d.servicesToday||0],['Agenda da semana',d.eventsWeek||0],['Entregas em andamento',d.projectsActive||0]];const el=document.getElementById("metrics");el.replaceChildren();for(const [name,value] of values){const c=document.createElement("article");c.className="metric";c.innerHTML=`<small>${name}</small><strong>${Number(value).toLocaleString('pt-BR')}</strong><span>Atualizado agora</span>`;el.append(c)}for(const [id,items,label] of [['demandList',d.demands||[],'Nenhuma demanda cadastrada.'],['agendaList',d.events||[],'Nenhum compromisso próximo.']]){const box=document.getElementById(id);box.replaceChildren();if(!items.length){const p=document.createElement('p');p.className='empty';p.textContent=label;box.append(p)}for(const item of items){const row=document.createElement('div');row.className='item';const strong=document.createElement('strong');strong.textContent=item.title;const span=document.createElement('span');span.textContent=item.subtitle||'';row.append(strong,span);box.append(row)}}}
try{const {session,profile}=await politappAuthReady;const role=profile?.grupo||"operacoes",user=session?.user||{};document.getElementById("roleLabel").textContent=ROLE_LABEL[role]||role;document.getElementById("officeName").textContent=profile?.unidade_nome||"Gabinete central";document.getElementById("userName").textContent=user.nome||user.email||"Usuário";document.getElementById("userInitial").textContent=(user.nome||user.email||"U").charAt(0).toUpperCase();menu(role);document.getElementById("loading").hidden=true;document.getElementById("dashboard").hidden=false;active("dashboard");const data=await api("summary").catch(()=>({}));renderSummary(data.ok?data:{});document.querySelectorAll("[data-go]").forEach(b=>b.addEventListener("click",()=>openModule(b.dataset.go,role)));document.getElementById("logout").addEventListener("click",e=>window.politappLogout?.(e));document.getElementById("mobileMenu").addEventListener("click",()=>document.querySelector(".sidebar").classList.toggle("open"))}catch{location.replace("/login.html?next=erp/")}
