import { politappAuthReady } from "../js/auth-guard.js?v=20260907-2";
const extraStyle=document.createElement("link");extraStyle.rel="stylesheet";extraStyle.href="forms.css?v=20260907-2";document.head.append(extraStyle);
const MODULES=[{id:"dashboard",label:"Visão geral",roles:["admin","gestao","operacoes"]},{id:"demands",label:"Demandas e protocolos",roles:["admin","gestao","operacoes"]},{id:"citizens",label:"Cidadãos e lideranças",roles:["admin","gestao","operacoes"]},{id:"events",label:"Agenda institucional",roles:["admin","gestao","operacoes"]},{id:"projects",label:"Projetos e entregas",roles:["admin","gestao"]},{id:"communications",label:"Comunicação",roles:["admin","gestao"]},{id:"territories",label:"Territórios",roles:["admin","gestao"]},{id:"reports",label:"Relatórios",roles:["admin","gestao"]},{id:"users",label:"Administração e RBAC",roles:["admin"]}];
const FORMS={
  demands:{title:"Nova demanda",fields:[['title','Assunto','text',true],['category','Categoria','text'],['priority','Prioridade','select',['normal','baixa','alta','urgente']],['status','Situação','select',['aberta','triagem','em_andamento','aguardando','resolvida']],['due_at','Prazo','datetime-local'],['description','Descrição','textarea']]},
  citizens:{title:"Novo cidadão ou liderança",fields:[['name','Nome','text',true],['email','E-mail','email'],['phone','Telefone','tel'],['neighborhood','Bairro','text'],['city','Município','text'],['state','UF','text']]},
  events:{title:"Novo compromisso",fields:[['title','Título','text',true],['starts_at','Início','datetime-local',true],['ends_at','Término','datetime-local'],['location','Local','text'],['status','Situação','select',['confirmado','provisorio','cancelado']],['description','Observações','textarea']]},
  projects:{title:"Novo projeto ou entrega",fields:[['title','Título','text',true],['status','Situação','select',['planejamento','em_andamento','concluido','suspenso']],['budget_cents','Orçamento em centavos','number'],['starts_at','Início','datetime-local'],['due_at','Prazo','datetime-local'],['description','Descrição','textarea']]},
  communications:{title:"Novo conteúdo",fields:[['title','Título','text',true],['channel','Canal','select',['social','facebook','instagram','whatsapp','imprensa','email']],['status','Situação','select',['rascunho','revisao','aprovado','publicado','cancelado']],['scheduled_at','Agendamento','datetime-local'],['content','Conteúdo','textarea']]}
};
const ROLE_LABEL={admin:"Administrador",gestao:"Gestão",operacoes:"Operações"};let currentRole="operacoes";
const token=()=>localStorage.getItem("politapp_token")||"";const el=id=>document.getElementById(id);function make(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
async function api(resource,{method="GET",body={}}={}){const auth=token();const url=`/api/erp/${resource}${method==="GET"&&auth?`?_token=${encodeURIComponent(auth)}`:""}`;const payload=method==="GET"?undefined:JSON.stringify({...body,_token:auth});const r=await fetch(url,{method,credentials:"include",cache:"no-store",headers:payload?{"Content-Type":"application/json"}:undefined,body:payload});const data=await r.json().catch(()=>({}));if(!r.ok||!data.ok)throw new Error(data.error||"Não foi possível concluir.");return data}
function toast(message,error=false){const box=el("toast");box.textContent=message;box.className=`toast show${error?" error":""}`;box.hidden=false;setTimeout(()=>{box.hidden=true;box.className="toast"},3500)}
function setActive(id){document.querySelectorAll("#erpMenu button").forEach(b=>b.classList.toggle("active",b.dataset.module===id))}
function buildMenu(){const nav=el("erpMenu");nav.replaceChildren();for(const m of MODULES.filter(x=>x.roles.includes(currentRole))){const b=make("button","",m.label);b.dataset.module=m.id;b.addEventListener("click",()=>openModule(m.id));nav.append(b)}}
function inputFor([name,label,type,extra]){const wrap=make("label","field"),caption=make("span","",label);let input;if(type==="textarea")input=document.createElement("textarea");else if(type==="select"){input=document.createElement("select");for(const option of extra){const o=new Option(option.replaceAll('_',' '),option);input.append(o)}}else{input=document.createElement("input");input.type=type||"text"}input.name=name;if(extra===true)input.required=true;wrap.append(caption,input);return wrap}
function displayValue(item){return item.title||item.name||"Registro"}function subtitle(resource,item){if(resource==="demands")return `${item.priority} · ${item.status} · ${item.category||'geral'}`;if(resource==="citizens")return [item.phone,item.neighborhood,item.city].filter(Boolean).join(" · ")||"Sem contato informado";if(resource==="events")return `${new Date(item.starts_at).toLocaleString('pt-BR')} ${item.location?`· ${item.location}`:''}`;if(resource==="projects")return `${item.status} · prazo ${item.due_at?new Date(item.due_at).toLocaleDateString('pt-BR'):'não definido'}`;if(resource==="communications")return `${item.channel} · ${item.status}`;return Object.entries(item).filter(([k])=>!['id','office_id'].includes(k)).slice(0,3).map(([,v])=>v).join(" · ")}
async function renderCrud(resource){const view=el("moduleView"),schema=FORMS[resource];view.replaceChildren();const toolbar=make("div","module-toolbar"),hint=make("p","muted","Cadastros do gabinete, isolados por unidade e protegidos por perfil."),add=make("button","primary","+ Adicionar");toolbar.append(hint,add);view.append(toolbar);const formCard=make("section","card form-card");formCard.hidden=true;const h=make("h3","",schema.title),form=make("form","erp-form");for(const field of schema.fields)form.append(inputFor(field));const formActions=make("div","form-actions"),save=make("button","primary","Salvar"),cancel=make("button","secondary","Cancelar");save.type="submit";cancel.type="button";formActions.append(save,cancel);form.append(formActions);formCard.append(h,form);view.append(formCard);const list=make("section","card list-card","Carregando…");view.append(list);add.onclick=()=>{form.reset();formCard.hidden=false;form.querySelector('input,select,textarea')?.focus()};cancel.onclick=()=>formCard.hidden=true;form.onsubmit=async event=>{event.preventDefault();save.disabled=true;try{const data=Object.fromEntries(new FormData(form));await api(resource,{method:"POST",body:data});toast("Registro salvo com sucesso.");formCard.hidden=true;await loadList()}catch(e){toast(e.message,true)}finally{save.disabled=false}};async function loadList(){try{const data=await api(resource);list.replaceChildren();const head=make("div","list-head"),title=make("h3","",`${data.items.length} registro(s)`),search=document.createElement("input");search.placeholder="Filtrar nesta lista";head.append(title,search);list.append(head);const rows=make("div","data-list");for(const item of data.items){const row=make("article","data-row"),text=make("div"),strong=make("strong","",displayValue(item)),small=make("span","",subtitle(resource,item)),actions=make("div","row-actions");text.append(strong,small);if(resource==="demands"&&item.status!=="resolvida"){const done=make("button","secondary","Resolver");done.onclick=async()=>{try{await api(resource,{method:"PATCH",body:{id:item.id,status:"resolvida"}});toast("Demanda resolvida.");await loadList()}catch(e){toast(e.message,true)}};actions.append(done)}row.dataset.search=`${displayValue(item)} ${subtitle(resource,item)}`.toLowerCase();row.append(text,actions);rows.append(row)}if(!data.items.length)rows.append(make("p","empty","Nenhum registro. Use “Adicionar” para começar."));list.append(rows);search.oninput=()=>rows.querySelectorAll('.data-row').forEach(r=>r.hidden=!r.dataset.search.includes(search.value.toLowerCase()))}catch(e){list.replaceChildren(make("p","empty",e.message))}}await loadList()}
async function renderSpecial(resource){const view=el("moduleView");view.replaceChildren(make("section","card state","Carregando indicadores…"));try{const data=await api(resource),items=data.items||[];view.replaceChildren();if(resource==="reports"){const grid=make("div","module-grid");for(const [title,rows] of [["Demandas por situação",data.status||[]],["Principais categorias",data.categories||[]]]){const card=make("article","card"),h=make("h3","",title);card.append(h);for(const row of rows)card.append(make("div","report-row",`${row.status||row.category}: ${row.total}`));if(!rows.length)card.append(make("p","empty","Sem dados para este relatório."));grid.append(card)}view.append(grid);return}const card=make("section","card"),h=make("h3","",resource==="territories"?"Cobertura territorial":"Usuários e permissões");card.append(h);for(const item of items){const row=make("article","data-row"),text=make("div");text.append(make("strong","",resource==="territories"?`${item.neighborhood} — ${item.city}`:item.name),make("span","",resource==="territories"?`${item.citizens} cidadão(s) · ${item.demands} demanda(s)`: `${item.email} · ${ROLE_LABEL[item.role]||item.role}`));row.append(text);card.append(row)}if(!items.length)card.append(make("p","empty","Nenhum dado disponível."));view.append(card)}catch(e){view.replaceChildren(make("section","card empty",e.message))}}
async function openModule(id){setActive(id);document.querySelector(".sidebar").classList.remove("open");el("pageTitle").textContent=MODULES.find(x=>x.id===id)?.label||"ERP";el("breadcrumb").textContent=`Gestão / ${el("pageTitle").textContent}`;if(id==="dashboard"){el("dashboard").hidden=false;el("moduleView").hidden=true;await loadSummary();return}el("dashboard").hidden=true;el("moduleView").hidden=false;if(FORMS[id])await renderCrud(id);else await renderSpecial(id)}
function renderSummary(d){const values=[['Demandas abertas',d.demandsOpen||0],['Atendimentos hoje',d.servicesToday||0],['Agenda da semana',d.eventsWeek||0],['Entregas em andamento',d.projectsActive||0]],metrics=el("metrics");metrics.replaceChildren();for(const [name,value] of values){const c=make("article","metric");c.append(make("small","",name),make("strong","",Number(value).toLocaleString('pt-BR')),make("span","","Atualizado agora"));metrics.append(c)}for(const [id,items,label] of [['demandList',d.demands||[],'Nenhuma demanda cadastrada.'],['agendaList',d.events||[],'Nenhum compromisso próximo.']]){const box=el(id);box.replaceChildren();for(const item of items){const row=make('div','item');row.append(make('strong','',item.title),make('span','',item.subtitle||''));box.append(row)}if(!items.length)box.append(make('p','empty',label))}}
async function loadSummary(){try{renderSummary(await api("summary"))}catch(e){toast(e.message,true);renderSummary({})}}
try{const {session,profile}=await politappAuthReady;currentRole=profile?.grupo||"operacoes";const user=session?.user||{};el("roleLabel").textContent=ROLE_LABEL[currentRole]||currentRole;el("officeName").textContent=profile?.unidade_nome||"Gabinete central";el("userName").textContent=user.nome||user.email||"Usuário";el("userInitial").textContent=(user.nome||user.email||"U").charAt(0).toUpperCase();buildMenu();el("loading").hidden=true;el("dashboard").hidden=false;setActive("dashboard");await loadSummary();document.querySelectorAll("[data-go]").forEach(b=>b.addEventListener("click",()=>openModule({demandas:'demands',cidadaos:'citizens',agenda:'events',comunicacao:'communications',relatorios:'reports'}[b.dataset.go]||b.dataset.go)));el("logout").addEventListener("click",e=>window.politappLogout?.(e));el("mobileMenu").addEventListener("click",()=>document.querySelector(".sidebar").classList.toggle("open"))}catch{location.replace("/login.html?next=erp/")}
