const node = (tag, className, text) => { const item = document.createElement(tag); if (className) item.className = className; if (text !== undefined) item.textContent = text; return item; };
const number = value => Number(value || 0).toLocaleString("pt-BR");
const money = value => (Number(value || 0) / 100).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const STATUS = { aberta: "Aberta", triagem: "Triagem", em_andamento: "Em andamento", aguardando: "Aguardando", resolvida: "Resolvida", arquivada: "Arquivada" };
const COLORS = ["#4f8cff", "#8c6cff", "#28c8a0", "#ffb54a", "#ef6688", "#60708c"];

function metric(label, value, detail, tone) { const card = node("article", `command-metric ${tone || ""}`); card.append(node("span", "metric-icon", tone === "good" ? "↗" : tone === "attention" ? "!" : "•"), node("small", "", label), node("strong", "", value), node("p", "", detail)); return card; }
function empty(text) { return node("p", "command-empty", text); }

function donut(rows) {
  const total = rows.reduce((sum, row) => sum + Number(row.total || 0), 0), card = node("article", "command-card status-card"), head = node("div", "command-card-head"); head.append(node("div", "", "Demandas por situação"), node("small", "", `${number(total)} no total`)); card.append(head);
  const body = node("div", "donut-layout"), chart = node("div", "donut-chart"), center = node("span"); center.append(node("strong", "", number(total)), node("small", "", "demandas")); chart.append(center);
  if (total) { let cursor = 0; const stops = rows.map((row, index) => { const start = cursor; cursor += Number(row.total) / total * 100; return `${COLORS[index % COLORS.length]} ${start}% ${cursor}%`; }); chart.style.background = `conic-gradient(${stops.join(",")})`; }
  const legend = node("div", "chart-legend"); rows.forEach((row, index) => { const item = node("div"); const label = node("span"); label.append(node("i", ""), document.createTextNode(STATUS[row.status] || String(row.status || "Sem situação").replaceAll("_", " "))); label.querySelector("i").style.background = COLORS[index % COLORS.length]; item.append(label, node("strong", "", number(row.total))); legend.append(item); }); if (!rows.length) legend.append(empty("Cadastre demandas para iniciar o gráfico.")); body.append(chart, legend); card.append(body); return card;
}

function bars(title, rows, labelKey = "label") { const card = node("article", "command-card bar-card"), head = node("div", "command-card-head"); head.append(node("div", "", title), node("small", "", "Visão operacional")); card.append(head); const max = Math.max(1, ...rows.map(row => Number(row.total || 0))), list = node("div", "horizontal-bars"); rows.forEach(row => { const line = node("div", "bar-line"), label = node("div"); label.append(node("span", "", row[labelKey] || "Geral"), node("strong", "", number(row.total))); const track = node("div", "bar-track"), fill = node("i"); fill.style.width = `${Number(row.total || 0) / max * 100}%`; track.append(fill); line.append(label, track); list.append(line); }); if (!rows.length) list.append(empty("Ainda não há dados para comparar.")); card.append(list); return card; }

function trend(rows) { const card = node("article", "command-card trend-card"), head = node("div", "command-card-head"); head.append(node("div", "", "Evolução das demandas"), node("small", "", "Últimos 6 meses")); card.append(head); const values = new Map(rows.map(row => [row.label, Number(row.total || 0)])), months = []; const today = new Date(); for (let offset = 5; offset >= 0; offset--) { const date = new Date(today.getFullYear(), today.getMonth() - offset, 1), key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`; months.push({ label: date.toLocaleDateString("pt-BR", { month: "short" }).replace(".", ""), value: values.get(key) || 0 }); } const max = Math.max(1, ...months.map(item => item.value)), chart = node("div", "trend-bars"); months.forEach(item => { const column = node("div", "trend-column"), value = node("span", "", number(item.value)), bar = node("i"); bar.style.height = `${Math.max(4, item.value / max * 100)}%`; bar.title = `${item.value} demanda(s)`; column.append(value, bar, node("small", "", item.label)); chart.append(column); }); card.append(chart); return card; }

function listCard(title, items, emptyText, actionLabel, action) { const card = node("article", "command-card list-command"), head = node("div", "command-card-head"), button = node("button", "text-action", actionLabel); button.onclick = action; head.append(node("div", "", title), button); card.append(head); const list = node("div", "command-list"); items.forEach(item => { const row = node("div"); row.append(node("i"), node("strong", "", item.title), node("span", "", item.subtitle || "")); list.append(row); }); if (!items.length) list.append(empty(emptyText)); card.append(list); return card; }

export function renderDashboardV2({ container, data, go }) {
  container.replaceChildren(); const hero = node("section", "command-hero"), heroCopy = node("div"); heroCopy.append(node("small", "", "POLITICAPP ERP · CENTRAL DE COMANDO"), node("h2", "", "Gestão política orientada por dados."), node("p", "", "Prioridades do gabinete, relacionamento, território e execução em uma visão única.")); const heroActions = node("div", "hero-actions"), demand = node("button", "primary", "+ Registrar demanda"), territory = node("button", "secondary", "Explorar territórios"); demand.onclick = () => go("demands"); territory.onclick = () => go("territories"); heroActions.append(demand, territory); hero.append(heroCopy, heroActions); container.append(hero);
  const metrics = node("section", "command-metrics"); metrics.append(metric("Demandas abertas", number(data.demandsOpen), "Fila ativa do gabinete", data.demandsOpen ? "attention" : "good"), metric("Cidadãos e lideranças", number(data.citizensTotal), "Base de relacionamento", "info"), metric("Municípios alcançados", number(data.territoriesTotal), "Cobertura territorial", "good"), metric("Projetos ativos", number(data.projectsActive), "Entregas em andamento", "info"), metric("Agenda da semana", number(data.eventsWeek), "Próximos 7 dias", "attention")); container.append(metrics);
  const charts = node("section", "command-grid charts-grid"); charts.append(trend(data.trend || []), donut(data.demandStatus || []), bars("Principais temas", data.categories || [])); container.append(charts);
  const financeRows = data.finance || [], receive = financeRows.filter(row => row.type === "receber").reduce((sum, row) => sum + Number(row.total || 0), 0), pay = financeRows.filter(row => row.type === "pagar").reduce((sum, row) => sum + Number(row.total || 0), 0), balance = receive - pay;
  const lower = node("section", "command-grid lower-grid"), finance = node("article", "command-card finance-command"), financeHead = node("div", "command-card-head"); financeHead.append(node("div", "", "Visão financeira"), node("small", "", "Lançamentos cadastrados")); finance.append(financeHead); const financeValues = node("div", "finance-values"); [["A receber", receive], ["A pagar", pay], ["Saldo projetado", balance]].forEach(([label, value]) => { const item = node("div"); item.append(node("small", "", label), node("strong", value < 0 ? "negative" : "", money(value))); financeValues.append(item); }); finance.append(financeValues); lower.append(finance, listCard("Demandas prioritárias", data.demands || [], "Nenhuma demanda prioritária.", "Ver demandas", () => go("demands")), listCard("Próximos compromissos", data.events || [], "Nenhum compromisso próximo.", "Abrir agenda", () => go("events"))); container.append(lower);
}
