import { renderCrudV2 } from "./crud-v2.js?v=20260907-11";

const make = (tag, className, text) => { const element = document.createElement(tag); if (className) element.className = className; if (text !== undefined) element.textContent = text; return element; };
const money = value => (Number(value || 0) / 100).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const STATUS = { disponivel: "Disponível", em_uso: "Em uso", manutencao: "Manutenção", inativo: "Inativo" };
const COLORS = { disponivel: "#28c8a0", em_uso: "#4f8cff", manutencao: "#ffb54a", inativo: "#69778f" };

function stat(label, value, detail, tone = "blue") { const card = make("article", `fleet-stat ${tone}`); card.append(make("small", "", label), make("strong", "", value), make("span", "", detail)); return card; }

function fleetDonut(vehicles) {
  const counts = Object.fromEntries(Object.keys(STATUS).map(status => [status, vehicles.filter(vehicle => vehicle.status === status).length])), total = vehicles.length, card = make("article", "finance-panel fleet-status-panel"), head = make("div", "finance-panel-head"); head.append(make("div", "", "Situação da frota"), make("small", "", `${total} veículo(s)`)); card.append(head); const layout = make("div", "fleet-donut-layout"), donut = make("div", "fleet-donut"), center = make("span"); center.append(make("strong", "", String(total)), make("small", "", "veículos")); donut.append(center); if (total) { let cursor = 0; donut.style.background = `conic-gradient(${Object.entries(counts).map(([status, count]) => { const start = cursor; cursor += count / total * 100; return `${COLORS[status]} ${start}% ${cursor}%`; }).join(",")})`; } const legend = make("div", "fleet-legend"); Object.entries(counts).forEach(([status, count]) => { const item = make("div"); const label = make("span"); const dot = make("i"); dot.style.background = COLORS[status]; label.append(dot, document.createTextNode(STATUS[status])); item.append(label, make("strong", "", String(count))); legend.append(item); }); layout.append(donut, legend); card.append(layout); return card;
}

function cashChart(items) {
  const card = make("article", "finance-panel cash-chart-panel"), head = make("div", "finance-panel-head"); head.append(make("div", "", "Fluxo financeiro"), make("small", "", "Últimos 6 meses")); card.append(head); const months = [], current = new Date(); for (let offset = 5; offset >= 0; offset--) { const date = new Date(current.getFullYear(), current.getMonth() - offset, 1), key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`; months.push({ key, label: date.toLocaleDateString("pt-BR", { month: "short" }).replace(".", ""), pagar: 0, receber: 0 }); } for (const item of items) { const key = String(item.due_date || item.created_at || "").slice(0, 7), month = months.find(entry => entry.key === key); if (month && (item.type === "pagar" || item.type === "receber")) month[item.type] += Number(item.amount_cents || 0); } const max = Math.max(1, ...months.flatMap(month => [month.pagar, month.receber])), chart = make("div", "cash-bars"); months.forEach(month => { const column = make("div", "cash-month"), bars = make("div", "cash-pair"), receive = make("i", "receive"), pay = make("i", "pay"); receive.style.height = `${Math.max(3, month.receber / max * 100)}%`; pay.style.height = `${Math.max(3, month.pagar / max * 100)}%`; receive.title = `Receber: ${money(month.receber)}`; pay.title = `Pagar: ${money(month.pagar)}`; bars.append(receive, pay); column.append(bars, make("small", "", month.label)); chart.append(column); }); card.append(chart); const legend = make("div", "cash-legend"); legend.append(make("span", "receive", "● Receber"), make("span", "pay", "● Pagar")); card.append(legend); return card;
}

function maintenancePanel(vehicles) {
  const card = make("article", "finance-panel maintenance-panel"), head = make("div", "finance-panel-head"); head.append(make("div", "", "Controle da frota"), make("small", "", "Próximas manutenções")); card.append(head); const alerts = vehicles.filter(vehicle => vehicle.status === "manutencao" || vehicle.next_maintenance).sort((a, b) => String(a.next_maintenance || "9999").localeCompare(String(b.next_maintenance || "9999"))).slice(0, 6), list = make("div", "maintenance-list"); alerts.forEach(vehicle => { const row = make("div"), badge = make("span", `vehicle-status ${vehicle.status}`, STATUS[vehicle.status] || vehicle.status); row.append(make("strong", "", `${vehicle.plate} · ${vehicle.model || vehicle.make || "Veículo"}`), make("small", "", vehicle.next_maintenance ? `Revisão: ${new Date(`${vehicle.next_maintenance}T12:00:00`).toLocaleDateString("pt-BR")}` : "Em manutenção"), badge); list.append(row); }); if (!alerts.length) list.append(make("p", "finance-empty", "Nenhuma manutenção programada.")); card.append(list); return card;
}

async function overview(body, api, toast) {
  body.replaceChildren(make("div", "finance-loading", "Atualizando visão financeira…"));
  try { const [{ items: finances = [] }, { items: vehicles = [] }] = await Promise.all([api("finances"), api("vehicles")]), receive = finances.filter(item => item.type === "receber" && !["cancelado"].includes(item.status)).reduce((sum, item) => sum + Number(item.amount_cents || 0), 0), pay = finances.filter(item => item.type === "pagar" && !["cancelado"].includes(item.status)).reduce((sum, item) => sum + Number(item.amount_cents || 0), 0), maintenance = vehicles.filter(vehicle => vehicle.status === "manutencao").length, fleetCost = vehicles.reduce((sum, vehicle) => sum + Number(vehicle.monthly_cost_cents || 0), 0); body.replaceChildren(); const stats = make("section", "fleet-stats"); stats.append(stat("Saldo projetado", money(receive - pay), "Receitas menos despesas", receive - pay >= 0 ? "green" : "red"), stat("Total da frota", String(vehicles.length), "Veículos cadastrados"), stat("Em manutenção", String(maintenance), maintenance ? "Requer atenção" : "Operação regular", maintenance ? "amber" : "green"), stat("Custo mensal da frota", money(fleetCost), "Estimativa cadastrada", "violet")); body.append(stats); const grid = make("section", "finance-overview-grid"); grid.append(cashChart(finances), fleetDonut(vehicles), maintenancePanel(vehicles)); body.append(grid); } catch (error) { body.replaceChildren(make("p", "finance-empty", error.message)); toast(error.message, true); }
}

export async function renderFinanceV2({ view, api, toast, financeSchema, vehicleSchema, displayValue, subtitle }) {
  view.replaceChildren(); const header = make("div", "finance-header"), copy = make("div"); copy.append(make("p", "eyebrow-small", "FINANÇAS E PATRIMÔNIO"), make("h2", "module-title", "Gestão financeira e de veículos"), make("p", "finance-intro", "Controle fluxo de caixa, frota, responsáveis, custos e manutenção.")); const tabs = make("div", "finance-tabs"), body = make("div", "finance-body"); const options = [["overview", "Visão geral"], ["entries", "Lançamentos"], ["vehicles", "Veículos"]], buttons = new Map(); options.forEach(([id, label]) => { const button = make("button", id === "overview" ? "active" : "", label); button.onclick = () => show(id); buttons.set(id, button); tabs.append(button); }); header.append(copy, tabs); view.append(header, body);
  async function show(id) { buttons.forEach((button, key) => button.classList.toggle("active", key === id)); if (id === "entries") return renderCrudV2({ view: body, resource: "finances", schema: financeSchema, api, toast, displayValue, subtitle }); if (id === "vehicles") return renderCrudV2({ view: body, resource: "vehicles", schema: vehicleSchema, api, toast, displayValue, subtitle }); return overview(body, api, toast); }
  await show("overview");
}
