const AUTH_ME="https://cmbusinesstoken.com/politicapp/php/auth/me.php";
const ACCESS={summary:["admin","gestao","operacoes"],tasks:["admin","gestao","operacoes"],demands:["admin","gestao","operacoes"],citizens:["admin","gestao","operacoes"],services:["admin","gestao","operacoes"],events:["admin","gestao","operacoes"],projects:["admin","gestao"],communications:["admin","gestao"],finances:["admin","gestao"],territories:["admin","gestao"],reports:["admin","gestao"],users:["admin"]};
const MODELS={
  tasks:{table:"erp_tasks",fields:["title","description","status","priority","assigned_to","due_date"],required:"title",order:"CASE status WHEN 'fazendo' THEN 0 WHEN 'hoje' THEN 1 WHEN 'aguardando' THEN 2 WHEN 'concluida' THEN 3 ELSE 4 END, due_date",creator:true},
  finances:{table:"erp_financial",fields:["type","description","category","party","amount_cents","due_date","status","paid_at","notes"],required:"description",order:"due_date",creator:true},
  services:{table:"erp_services",fields:["channel","notes","citizen_id","demand_id"],required:"notes",order:"created_at DESC",creator:true},
  demands:{table:"erp_demands",fields:["title","description","category","priority","status","citizen_id","assignee_id","due_at"],required:"title",order:"created_at DESC"},
  citizens:{table:"erp_citizens",fields:["name","email","phone","neighborhood","city","state","tags","consent_at"],required:"name",order:"name"},
  events:{table:"erp_events",fields:["title","description","starts_at","ends_at","location","owner_id","status"],required:"title",order:"starts_at"},
  projects:{table:"erp_projects",fields:["title","description","status","owner_id","budget_cents","starts_at","due_at"],required:"title",order:"created_at DESC"},
  communications:{table:"erp_communications",fields:["title","channel","status","content","scheduled_at","owner_id"],required:"title",order:"created_at DESC"}
};
function response(data,status=200){return Response.json(data,{status,headers:{"Cache-Control":"no-store"}})}
function sameOrigin(request){const origin=request.headers.get("Origin");return !origin||origin===new URL(request.url).origin}
async function requestBody(request){if(request.method==="GET")return {};if(Number(request.headers.get("content-length")||0)>65536)throw new Error("body_too_large");return request.clone().json().catch(()=>({}))}
async function identity(request,body){const url=new URL(request.url),token=String(url.searchParams.get("_token")||body._token||"");if(!token)return null;const auth=new URL(AUTH_ME);auth.searchParams.set("_token",token);const result=await fetch(auth,{headers:{Accept:"application/json"},signal:AbortSignal.timeout(8000)});if(!result.ok)return null;const data=await result.json();if(!data.ok||!data.autenticado||data.profile?.conta_status!=="aprovado")return null;return {user:data.user||{},profile:data.profile}}
async function connect(env){if(!env.ERP_MYSQL)return null;const {createConnection}=await import("mysql2/promise");return createConnection({host:env.ERP_MYSQL.host,user:env.ERP_MYSQL.user,password:env.ERP_MYSQL.password,database:env.ERP_MYSQL.database,port:env.ERP_MYSQL.port,disableEval:true,connectTimeout:10000})}
function clean(model,body){const values={};for(const field of model.fields){if(body[field]===undefined)continue;let value=body[field];if(field==="tags"&&typeof value!=="string")value=JSON.stringify(value);if(typeof value==="string")value=value.trim().slice(0,field==="description"||field==="content"?10000:500);values[field]=value===""?null:value}return values}
async function audit(db,office,user,action,entity,id){await db.execute("INSERT INTO erp_audit(id,office_id,user_id,action,entity,entity_id) VALUES(?,?,?,?,?,?)",[crypto.randomUUID(),office,String(user.id||user.email||"unknown"),action,entity,id])}

async function summary(db,office){const [[counts],[demands],[events]]=await Promise.all([
  db.execute("SELECT (SELECT count(*) FROM erp_demands WHERE office_id=? AND status NOT IN ('resolvida','arquivada')) demands_open,(SELECT count(*) FROM erp_services WHERE office_id=? AND date(created_at)=UTC_DATE()) services_today,(SELECT count(*) FROM erp_events WHERE office_id=? AND starts_at>=UTC_TIMESTAMP() AND starts_at<DATE_ADD(UTC_TIMESTAMP(),INTERVAL 7 DAY)) events_week,(SELECT count(*) FROM erp_projects WHERE office_id=? AND status='em_andamento') projects_active",[office,office,office,office]),
  db.execute("SELECT title,concat(priority,' · ',status) subtitle FROM erp_demands WHERE office_id=? AND status NOT IN ('resolvida','arquivada') ORDER BY FIELD(priority,'urgente','alta','normal','baixa'),created_at DESC LIMIT 5",[office]),
  db.execute("SELECT title,concat(date_format(starts_at,'%d/%m %H:%i'),if(location IS NULL OR location='','',concat(' · ',location))) subtitle FROM erp_events WHERE office_id=? AND starts_at>=UTC_TIMESTAMP() ORDER BY starts_at LIMIT 5",[office])
]);const c=counts[0]||{};return {ok:true,storage:"mysql",demandsOpen:Number(c.demands_open||0),servicesToday:Number(c.services_today||0),eventsWeek:Number(c.events_week||0),projectsActive:Number(c.projects_active||0),demands,events}}
async function special(db,resource,office,account){
  if(resource==="summary")return summary(db,office);
  if(resource==="territories"){const [rows]=await db.execute("SELECT coalesce(nullif(city,''),'Não informado') city,coalesce(nullif(neighborhood,''),'Não informado') neighborhood,count(*) citizens,(SELECT count(*) FROM erp_demands d WHERE d.office_id=? AND d.citizen_id IN(SELECT id FROM erp_citizens c2 WHERE c2.office_id=? AND coalesce(c2.city,'')=coalesce(c.city,'') AND coalesce(c2.neighborhood,'')=coalesce(c.neighborhood,''))) demands FROM erp_citizens c WHERE office_id=? GROUP BY city,neighborhood ORDER BY citizens DESC LIMIT 100",[office,office,office]);return {ok:true,items:rows}}
  if(resource==="reports"){const [status]=await db.execute("SELECT status,count(*) total FROM erp_demands WHERE office_id=? GROUP BY status",[office]);const [categories]=await db.execute("SELECT category,count(*) total FROM erp_demands WHERE office_id=? GROUP BY category ORDER BY total DESC LIMIT 10",[office]);return {ok:true,status,categories}}
  if(resource==="users")return {ok:true,items:[{id:account.user.id||"",name:account.user.nome||account.user.email||"Usuário",email:account.user.email||"",role:account.profile.grupo,officeId:account.profile.unidade_id||"central"}]};
  return null;
}
async function d1Request(db,request,resource,office,account,body){
  if(resource==="summary"){
    const [counts,demands,events]=await Promise.all([
      db.prepare("SELECT (SELECT count(*) FROM erp_demands WHERE office_id=?1 AND status NOT IN ('resolvida','arquivada')) demands_open,(SELECT count(*) FROM erp_services WHERE office_id=?1 AND date(created_at)=date('now')) services_today,(SELECT count(*) FROM erp_events WHERE office_id=?1 AND starts_at>=datetime('now') AND starts_at<datetime('now','+7 day')) events_week,(SELECT count(*) FROM erp_projects WHERE office_id=?1 AND status='em_andamento') projects_active").bind(office).first(),
      db.prepare("SELECT title,priority||' · '||status subtitle FROM erp_demands WHERE office_id=?1 AND status NOT IN ('resolvida','arquivada') ORDER BY CASE priority WHEN 'urgente' THEN 0 WHEN 'alta' THEN 1 ELSE 2 END,created_at DESC LIMIT 5").bind(office).all(),
      db.prepare("SELECT title,strftime('%d/%m %H:%M',starts_at)||coalesce(' · '||location,'') subtitle FROM erp_events WHERE office_id=?1 AND starts_at>=datetime('now') ORDER BY starts_at LIMIT 5").bind(office).all()
    ]);return {ok:true,storage:"d1",demandsOpen:counts?.demands_open||0,servicesToday:counts?.services_today||0,eventsWeek:counts?.events_week||0,projectsActive:counts?.projects_active||0,demands:demands.results||[],events:events.results||[]};
  }
  if(resource==="territories"){const rows=await db.prepare("SELECT coalesce(nullif(c.city,''),'Não informado') city,coalesce(nullif(c.neighborhood,''),'Não informado') neighborhood,count(*) citizens,(SELECT count(*) FROM erp_demands d JOIN erp_citizens x ON x.id=d.citizen_id WHERE d.office_id=?1 AND coalesce(x.city,'')=coalesce(c.city,'') AND coalesce(x.neighborhood,'')=coalesce(c.neighborhood,'')) demands FROM erp_citizens c WHERE c.office_id=?1 GROUP BY c.city,c.neighborhood ORDER BY citizens DESC LIMIT 100").bind(office).all();return {ok:true,items:rows.results||[]}}
  if(resource==="reports"){const [status,categories]=await Promise.all([db.prepare("SELECT status,count(*) total FROM erp_demands WHERE office_id=? GROUP BY status").bind(office).all(),db.prepare("SELECT category,count(*) total FROM erp_demands WHERE office_id=? GROUP BY category ORDER BY total DESC LIMIT 10").bind(office).all()]);return {ok:true,status:status.results||[],categories:categories.results||[]}}
  if(resource==="users")return {ok:true,items:[{id:account.user.id||"",name:account.user.nome||account.user.email||"Usuário",email:account.user.email||"",role:account.profile.grupo,officeId:office}]};
  const model=MODELS[resource];if(!model)throw new Error("unsupported");
  if(request.method==="GET"){const rows=await db.prepare(`SELECT * FROM ${model.table} WHERE office_id=? ORDER BY ${model.order} LIMIT 200`).bind(office).all();return {ok:true,items:rows.results||[]}}
  if(request.method==="DELETE"){const id=String(body.id||"");if(!id)return {ok:false,status:400,error:"Informe o registro."};const result=await db.prepare(`DELETE FROM ${model.table} WHERE id=? AND office_id=?`).bind(id,office).run();if(!result.meta?.changes)return {ok:false,status:404,error:"Registro não encontrado."};await db.prepare("INSERT INTO erp_audit(id,office_id,user_id,action,entity,entity_id) VALUES(?,?,?,?,?,?)").bind(crypto.randomUUID(),office,String(account.user.id||account.user.email||"unknown"),"delete",resource,id).run();return {ok:true,id}}
  const values=clean(model,body);
  if(request.method==="POST"){if(!values[model.required])return {ok:false,status:400,error:"Preencha os campos obrigatórios."};const id=crypto.randomUUID(),fields=["id","office_id",...Object.keys(values)],paramsValues=[id,office,...Object.values(values)];if(model.table==="erp_demands"||model.creator){fields.push("created_by");paramsValues.push(String(account.user.id||account.user.email||"unknown"))}await db.prepare(`INSERT INTO ${model.table}(${fields.join(",")}) VALUES(${fields.map(()=>"?").join(",")})`).bind(...paramsValues).run();await db.prepare("INSERT INTO erp_audit(id,office_id,user_id,action,entity,entity_id) VALUES(?,?,?,?,?,?)").bind(crypto.randomUUID(),office,String(account.user.id||account.user.email||"unknown"),"create",resource,id).run();return {ok:true,id,status:201}}
  const id=String(body.id||"");if(!id||!Object.keys(values).length)return {ok:false,status:400,error:"Nada para atualizar."};const result=await db.prepare(`UPDATE ${model.table} SET ${Object.keys(values).map(field=>`${field}=?`).join(",")} WHERE id=? AND office_id=?`).bind(...Object.values(values),id,office).run();if(!result.meta?.changes)return {ok:false,status:404,error:"Registro não encontrado."};await db.prepare("INSERT INTO erp_audit(id,office_id,user_id,action,entity,entity_id) VALUES(?,?,?,?,?,?)").bind(crypto.randomUUID(),office,String(account.user.id||account.user.email||"unknown"),"update",resource,id).run();return {ok:true,id};
}
export async function onRequest({request,params,env}){
  const resource=String(params.resource||"");if(!ACCESS[resource])return response({ok:false,error:"Módulo inexistente."},404);if(!["GET","POST","PATCH","DELETE"].includes(request.method))return response({ok:false,error:"Método não permitido."},405);if(request.method!=="GET"&&!sameOrigin(request))return response({ok:false,error:"Origem não autorizada."},403);
  let body;try{body=await requestBody(request)}catch{return response({ok:false,error:"Requisição muito grande."},413)}const account=await identity(request,body).catch(()=>null);if(!account)return response({ok:false,error:"Sessão inválida."},401);if(!ACCESS[resource].includes(account.profile.grupo))return response({ok:false,error:"Acesso não autorizado para este perfil."},403);if(!env.ERP_MYSQL&&!env.ERP_DB)return resource==="summary"?response({ok:true,setupRequired:true,demandsOpen:0,servicesToday:0,eventsWeek:0,projectsActive:0,demands:[],events:[]}):response({ok:false,error:"Banco ERP não vinculado."},503);
  const office=String(account.profile.unidade_id||"central");
  if(!env.ERP_MYSQL&&env.ERP_DB){try{const database=typeof env.ERP_DB.withSession==="function"?env.ERP_DB.withSession("first-primary"):env.ERP_DB;const result=await d1Request(database,request,resource,office,account,body);return response(result,result.status||200)}catch(error){console.error(JSON.stringify({event:"erp_d1_failed",resource,message:String(error)}));return response({ok:false,error:"Não foi possível concluir a operação."},500)}}
  const db=await connect(env).catch(()=>null);if(!db)return response({ok:false,error:"Banco ERP indisponível."},503);
  try{
    const specialResult=request.method==="GET"?await special(db,resource,office,account):null;if(specialResult)return response(specialResult);
    const model=MODELS[resource];if(!model)return response({ok:false,error:"Operação não disponível."},405);
    if(request.method==="GET"){const [rows]=await db.execute(`SELECT * FROM ${model.table} WHERE office_id=? ORDER BY ${model.order} LIMIT 200`,[office]);return response({ok:true,items:rows})}
    if(request.method==="DELETE"){const id=String(body.id||"");if(!id)return response({ok:false,error:"Informe o registro."},400);const [result]=await db.execute(`DELETE FROM ${model.table} WHERE id=? AND office_id=?`,[id,office]);if(!result.affectedRows)return response({ok:false,error:"Registro não encontrado."},404);await audit(db,office,account.user,"delete",resource,id);return response({ok:true,id})}
    const values=clean(model,body);if(request.method==="POST"){if(!values[model.required])return response({ok:false,error:"Preencha os campos obrigatórios."},400);const id=crypto.randomUUID(),fields=["id","office_id",...Object.keys(values)],paramsValues=[id,office,...Object.values(values)];if(model.table==="erp_demands"||model.creator){fields.push("created_by");paramsValues.push(String(account.user.id||account.user.email||"unknown"))}const marks=fields.map(()=>"?").join(",");await db.execute(`INSERT INTO ${model.table}(${fields.join(",")}) VALUES(${marks})`,paramsValues);await audit(db,office,account.user,"create",resource,id);return response({ok:true,id},201)}
    const id=String(body.id||"");if(!id||!Object.keys(values).length)return response({ok:false,error:"Nada para atualizar."},400);const changes=Object.keys(values).map(field=>`${field}=?`).join(",");const [result]=await db.execute(`UPDATE ${model.table} SET ${changes} WHERE id=? AND office_id=?`,[...Object.values(values),id,office]);if(!result.affectedRows)return response({ok:false,error:"Registro não encontrado."},404);await audit(db,office,account.user,"update",resource,id);return response({ok:true,id});
  }catch(error){console.error(JSON.stringify({event:"erp_request_failed",resource,message:String(error)}));return response({ok:false,error:"Não foi possível concluir a operação."},500)}finally{await db.end()}
}
